apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    matchLabels: storefront
  name: storefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storefront
  template:
    metadata:
      labels:
        app: storefront
    spec:
      containers:
        - env:
          - name: API_URL
            value: http://localhost:8000/graphql/
          image: amasr/saleor-platform_storefront:2.10
          name: storefront
          ports:
          - containerPort: 3000
      restartPolicy: Always
